// Generated by https://quicktype.io

export interface CTEResponse {
    id?:             string;
    transportadora?: string;
    site?:           string;
    nFe?:            string;
    cTe?:            string;
    valor?:          number;
    dataImportacao?: null | Date;
    ordemCompra?:    null | string;
    status?:         string;
    validacoes?:     ValidacoeResponse[];
}

export interface ValidacoeResponse {
    mensagem:     string;
    tipoMensagem: string;
}
